wordpress:
  image: wordpress
  ports:
    - ${public_port}:80
  environment:
    WORDPRESS_DB_HOST: ${db_host}
    WORDPRESS_DB_USER: ${db_user}
    WORDPRESS_DB_PASSWORD: ${db_password}
    WORDPRESS_DB_NAME:  ${db_name}